version: "3"
services:
  nginx:
    ports:
      - "3000:80"
  express-api-kit:
    build:
      context: .
      args:
        NODE_ENV: development
    volumes:
      - ./:/app
    environment:
      - NODE_ENV=development
    command: npm run dev
